//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""PLAY"",
            ""id"": ""dd9b691b-84a6-4bb0-801a-132645e0f313"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a19b979c-64d9-4b9f-8b83-65fd348c9c6f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovePressedD"",
                    ""type"": ""Button"",
                    ""id"": ""0c54a6f6-43e6-4566-abf2-9218a4cbf605"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedR"",
                    ""type"": ""Button"",
                    ""id"": ""fc18bde9-9db7-4114-8f1f-02ca7ed275d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedU"",
                    ""type"": ""Button"",
                    ""id"": ""fae81133-8a35-4c1e-8e7d-b825150c29ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedL"",
                    ""type"": ""Button"",
                    ""id"": ""29bfa6e9-f199-41c9-a176-fd81b57d43b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""b5c27e6c-250c-4203-930b-7b265948643c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""f7d0d03e-86d8-41ad-b293-b9d019377830"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""758867e9-54ec-4cb2-99d4-bc6efe9a220c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiSystem"",
                    ""type"": ""Button"",
                    ""id"": ""ba94ecbe-dc75-4cc1-ab72-b49fbb168a0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""4b6d098a-166e-4637-9f4f-84689c3642f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""6249f391-e078-4266-a086-e12366a9a346"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""64d444f1-fcd5-40a2-8499-e7cf65893ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti1"",
                    ""type"": ""Value"",
                    ""id"": ""4bf05f2d-c114-4d9b-87f3-23499db6b170"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Graffiti2"",
                    ""type"": ""Button"",
                    ""id"": ""dd21d9d8-77e4-4a4f-b109-79dc39e580f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti3"",
                    ""type"": ""Button"",
                    ""id"": ""8bb4bc52-f30c-407f-af63-e0958ffb0e50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti4"",
                    ""type"": ""Button"",
                    ""id"": ""918ff8cb-bfb4-4b2e-8753-fe0eb5d626f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti5"",
                    ""type"": ""Button"",
                    ""id"": ""c135f583-110f-4643-b758-977a5cdd278c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""fc979028-13d8-4f4d-bfed-375ac27a78aa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e0b16dea-a883-4135-bc68-3a13e0faf025"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6949ba90-5681-4630-a901-1b8505978c03"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aff9aa88-161f-4791-826c-80d087b76d75"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bc447105-c311-4245-a742-e249e318d33b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""56630960-e5d4-4b20-a59c-1217daddc051"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae781840-e157-477a-a7aa-9bdef01446fc"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""512bde2c-0a58-4744-9db4-6ac1702bd5ca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""238d8390-831c-4a1e-8a97-5ea2fd12c4d3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1070842e-e9d7-436e-a488-b56bba1d66cf"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ca26d5-0f2a-493c-9db2-b83235758c02"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42d0fd42-e3cb-4fb5-9773-1c5c1c3bac31"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87d95e25-f890-458d-b21d-34c318e31584"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71d1d5dc-6a04-4f4c-971e-9ce05a440736"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acaa6066-76eb-4aad-bd36-47cd1b0c69f4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80eb2c03-9a7b-48d7-995a-4e1eccc4dd92"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4de0847e-9d0a-4dfa-8201-7b3725d88d6f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c72195f-7aa0-4980-b841-efa3942502a2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa4421eb-3735-406f-a65e-a3d6c1176445"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""172e8014-cad4-400e-b154-705ccbff0709"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6837c169-ca4e-4d9f-8fed-d5d8ac83a7b3"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75263458-895e-4074-a599-a8e67466b2dc"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""212fdb9f-296c-4ad7-884a-b405a8ec35a0"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f635be5-5b0d-448a-8ddb-552fc090b6d9"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MENU"",
            ""id"": ""c746268e-2059-4935-98a0-106930dde527"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4405359a-76bb-498f-82f5-d3a6a92a16fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""62c7377b-8883-48d9-9eed-bff4c689253d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""6bfcc3ae-856c-4d6f-8738-1a95600012e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f6ea5efa-c362-44f1-b027-083b9e621883"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d9438fbd-b3a0-499d-9bce-89cd0305532f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7490f3e8-f946-48cb-9344-78df96e69dcd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""69d81480-4da2-4e39-9f28-9ec97213f795"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""66e0d2c6-635d-4450-80d6-ffafa92660d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9e1ff05e-b0ea-4e0a-9439-3c5c3097bb40"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8c9e535-58e8-42c0-8099-cf721642bbff"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""a1ee55f0-71cf-4d40-8e57-52bb50533c2d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8298001d-2552-4c5c-b526-9e666e4a0604"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""235c6a37-fbdf-4e55-99b3-530fdc579811"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cbcc913a-df99-42ed-a1ec-bb63d281df07"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""df4497a7-ad14-475b-858d-90520e85bc94"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4364dbc7-9f02-466c-8f3b-e3b9c665e28b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8ad99c0c-42c4-422f-b0ca-68a634006221"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4ab0c4f3-523a-486e-8b1a-9d6931471bc1"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e5f6329d-2dcc-494f-b67a-5715017596cc"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""38b5ed54-6d35-4554-8e33-724e5e4b7829"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""4f16dcfd-4775-4547-9aac-0b6340c34b17"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e93f630d-ba10-4988-9ae2-a4bf0658ff13"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""114a4b41-24ef-44b5-b0db-899e0bb060bd"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8f00ede6-4a97-4766-ba25-c7c58be6adca"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4663659e-9c27-49cb-a78d-225eb3c37130"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""90caac91-b24e-43e3-9d92-e4d139c08f16"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9348a8bf-aa71-4814-8fbe-1c56cbfb30b0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""255bcb9f-c0d5-4b20-b1fe-b739b3065616"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""84769a3c-21a7-454d-a029-c5087299fd19"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c53a5972-9592-4875-b2e1-4e8eee9ccc18"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""121678de-d8dd-4f9b-8d52-db9e2a53a84c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bae1100f-e20d-4c3d-b3e0-73b297021a1e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dd2fe64a-b1c3-43f2-b1fc-c0ddc65e2f2c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""10192e79-fb06-4912-93f2-fa1ac258f792"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""32c832e8-f4c8-4519-bb10-658ec44e7e57"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ad2c663-2815-4a0b-8086-5be78dfa4f2e"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73ac174-4d51-47b3-ac56-4adec09f6180"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0da2347-f9f9-4d45-903a-9a16a6e4af92"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""365f8195-54f9-4322-9d2b-42f33284fefe"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""507a390b-4fce-4ea0-a7e6-190f6bcb8de3"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc2411f7-0371-4d2e-9f5c-22128dd4d8a5"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e46a31f3-c821-42a8-b48d-424c338b16da"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b2981eb-1bc6-49d9-a228-e0bcedac6196"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61f3a120-93c7-4092-a9fa-fc2773551582"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b5014e9-b918-4453-8c97-09d9277d7005"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e4e486a-f770-4f77-856e-b4c4f3793532"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""190fcb93-0a70-4f89-b290-9ac88dc01961"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90036be6-f4ff-4694-9177-ff023e11db43"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e3d3073-ae88-484c-9134-ff23cda57312"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee3f9fa1-e894-49c9-bc2a-46bb36d97a62"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0869daad-e9f7-44fd-9787-2d94cdea7181"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GRAFFITI"",
            ""id"": ""1fb7457b-d495-4391-b079-9a6881d779a6"",
            ""actions"": [
                {
                    ""name"": ""MovePressedD"",
                    ""type"": ""Button"",
                    ""id"": ""c67a0f6f-abb2-4967-a654-5de439ab3aa9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedR"",
                    ""type"": ""Button"",
                    ""id"": ""de96fc54-d5d1-442b-b371-b9ad2a057908"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedU"",
                    ""type"": ""Button"",
                    ""id"": ""e0edcd01-28a9-4122-996d-e9952996faa4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePressedL"",
                    ""type"": ""Button"",
                    ""id"": ""d67ee295-59c4-438d-ac6b-623bf645da08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0b8c5b1f-7bf6-4c97-be9a-f86f17247752"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiSystem"",
                    ""type"": ""Button"",
                    ""id"": ""d66a3359-ccee-457e-8dee-e93575a3e6b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""0af3c09c-3553-4185-ba7a-44d50390d94e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""60da3b1f-6470-455d-8e1e-c62ec71d82ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti1"",
                    ""type"": ""Value"",
                    ""id"": ""1e58b2fe-933e-4ffc-864c-63b78c89e6a3"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Graffiti2"",
                    ""type"": ""Button"",
                    ""id"": ""e1e10630-e778-4325-9875-8915e9b08735"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti3"",
                    ""type"": ""Button"",
                    ""id"": ""bb475f7d-aebb-48c6-a12c-52a106369b65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti4"",
                    ""type"": ""Button"",
                    ""id"": ""611d9c06-6171-4a6a-8998-b99cbb2fd70e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graffiti5"",
                    ""type"": ""Button"",
                    ""id"": ""df7c7183-8134-4dc4-b961-f31e09c7757c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bc521ee0-bfdd-4d94-8879-af46445cbcf5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af747597-e991-49c3-8ee4-74ecc3aec1a4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad24f526-9456-4883-b520-338bdafc2f63"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d52d0514-382f-4f9e-a19c-0f93e4bcbd91"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePressedL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16935eb9-0196-4bf9-baf8-18143c4537a0"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d19b1df-3c85-4581-bb56-8c9e6dbda0c3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc535f72-7818-4c94-bd67-c49b14474096"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a6e79e9-488e-4a2f-b0ae-fbdf57fa24ca"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""751bd189-59fb-414e-bf62-ee18d7656bc8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be8f2101-47bb-476e-b14d-caa239493936"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1b5eb78-06a1-456e-a83b-8ac24161d853"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc41594b-c8c7-499f-abd0-a3c7b757b007"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""760decb7-5f58-4aa5-8bd5-7b81327c8823"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graffiti5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_TOGGLE"",
            ""id"": ""b8e31618-05ef-4916-b1cd-19e4100140ca"",
            ""actions"": [
                {
                    ""name"": ""OpenMap"",
                    ""type"": ""Button"",
                    ""id"": ""e5c9f26e-d36a-40d7-b832-f1094b7bcee9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenNote"",
                    ""type"": ""Button"",
                    ""id"": ""bc1325b6-7437-4280-841f-5fed1fbd9eeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCodex"",
                    ""type"": ""Button"",
                    ""id"": ""7533139f-7059-475a-8364-fc9191716e95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5090aa39-e924-45b5-8acd-44791a3f70e2"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a19db6c-ce5f-418b-a681-7f3271bc49e9"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenNote"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfbfb399-ea17-4057-af9e-96f84778dd91"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCodex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PLAY
        m_PLAY = asset.FindActionMap("PLAY", throwIfNotFound: true);
        m_PLAY_Move = m_PLAY.FindAction("Move", throwIfNotFound: true);
        m_PLAY_MovePressedD = m_PLAY.FindAction("MovePressedD", throwIfNotFound: true);
        m_PLAY_MovePressedR = m_PLAY.FindAction("MovePressedR", throwIfNotFound: true);
        m_PLAY_MovePressedU = m_PLAY.FindAction("MovePressedU", throwIfNotFound: true);
        m_PLAY_MovePressedL = m_PLAY.FindAction("MovePressedL", throwIfNotFound: true);
        m_PLAY_Sprint = m_PLAY.FindAction("Sprint", throwIfNotFound: true);
        m_PLAY_Attack = m_PLAY.FindAction("Attack", throwIfNotFound: true);
        m_PLAY_Dodge = m_PLAY.FindAction("Dodge", throwIfNotFound: true);
        m_PLAY_GraffitiSystem = m_PLAY.FindAction("GraffitiSystem", throwIfNotFound: true);
        m_PLAY_Menu = m_PLAY.FindAction("Menu", throwIfNotFound: true);
        m_PLAY_Confirm = m_PLAY.FindAction("Confirm", throwIfNotFound: true);
        m_PLAY_Skill = m_PLAY.FindAction("Skill", throwIfNotFound: true);
        m_PLAY_Graffiti1 = m_PLAY.FindAction("Graffiti1", throwIfNotFound: true);
        m_PLAY_Graffiti2 = m_PLAY.FindAction("Graffiti2", throwIfNotFound: true);
        m_PLAY_Graffiti3 = m_PLAY.FindAction("Graffiti3", throwIfNotFound: true);
        m_PLAY_Graffiti4 = m_PLAY.FindAction("Graffiti4", throwIfNotFound: true);
        m_PLAY_Graffiti5 = m_PLAY.FindAction("Graffiti5", throwIfNotFound: true);
        // MENU
        m_MENU = asset.FindActionMap("MENU", throwIfNotFound: true);
        m_MENU_Navigate = m_MENU.FindAction("Navigate", throwIfNotFound: true);
        m_MENU_Submit = m_MENU.FindAction("Submit", throwIfNotFound: true);
        m_MENU_Cancel = m_MENU.FindAction("Cancel", throwIfNotFound: true);
        m_MENU_Point = m_MENU.FindAction("Point", throwIfNotFound: true);
        m_MENU_Click = m_MENU.FindAction("Click", throwIfNotFound: true);
        m_MENU_ScrollWheel = m_MENU.FindAction("ScrollWheel", throwIfNotFound: true);
        m_MENU_MiddleClick = m_MENU.FindAction("MiddleClick", throwIfNotFound: true);
        m_MENU_RightClick = m_MENU.FindAction("RightClick", throwIfNotFound: true);
        m_MENU_TrackedDevicePosition = m_MENU.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_MENU_TrackedDeviceOrientation = m_MENU.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        // GRAFFITI
        m_GRAFFITI = asset.FindActionMap("GRAFFITI", throwIfNotFound: true);
        m_GRAFFITI_MovePressedD = m_GRAFFITI.FindAction("MovePressedD", throwIfNotFound: true);
        m_GRAFFITI_MovePressedR = m_GRAFFITI.FindAction("MovePressedR", throwIfNotFound: true);
        m_GRAFFITI_MovePressedU = m_GRAFFITI.FindAction("MovePressedU", throwIfNotFound: true);
        m_GRAFFITI_MovePressedL = m_GRAFFITI.FindAction("MovePressedL", throwIfNotFound: true);
        m_GRAFFITI_Attack = m_GRAFFITI.FindAction("Attack", throwIfNotFound: true);
        m_GRAFFITI_GraffitiSystem = m_GRAFFITI.FindAction("GraffitiSystem", throwIfNotFound: true);
        m_GRAFFITI_Skill = m_GRAFFITI.FindAction("Skill", throwIfNotFound: true);
        m_GRAFFITI_Cancel = m_GRAFFITI.FindAction("Cancel", throwIfNotFound: true);
        m_GRAFFITI_Graffiti1 = m_GRAFFITI.FindAction("Graffiti1", throwIfNotFound: true);
        m_GRAFFITI_Graffiti2 = m_GRAFFITI.FindAction("Graffiti2", throwIfNotFound: true);
        m_GRAFFITI_Graffiti3 = m_GRAFFITI.FindAction("Graffiti3", throwIfNotFound: true);
        m_GRAFFITI_Graffiti4 = m_GRAFFITI.FindAction("Graffiti4", throwIfNotFound: true);
        m_GRAFFITI_Graffiti5 = m_GRAFFITI.FindAction("Graffiti5", throwIfNotFound: true);
        // UI_TOGGLE
        m_UI_TOGGLE = asset.FindActionMap("UI_TOGGLE", throwIfNotFound: true);
        m_UI_TOGGLE_OpenMap = m_UI_TOGGLE.FindAction("OpenMap", throwIfNotFound: true);
        m_UI_TOGGLE_OpenNote = m_UI_TOGGLE.FindAction("OpenNote", throwIfNotFound: true);
        m_UI_TOGGLE_OpenCodex = m_UI_TOGGLE.FindAction("OpenCodex", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PLAY
    private readonly InputActionMap m_PLAY;
    private List<IPLAYActions> m_PLAYActionsCallbackInterfaces = new List<IPLAYActions>();
    private readonly InputAction m_PLAY_Move;
    private readonly InputAction m_PLAY_MovePressedD;
    private readonly InputAction m_PLAY_MovePressedR;
    private readonly InputAction m_PLAY_MovePressedU;
    private readonly InputAction m_PLAY_MovePressedL;
    private readonly InputAction m_PLAY_Sprint;
    private readonly InputAction m_PLAY_Attack;
    private readonly InputAction m_PLAY_Dodge;
    private readonly InputAction m_PLAY_GraffitiSystem;
    private readonly InputAction m_PLAY_Menu;
    private readonly InputAction m_PLAY_Confirm;
    private readonly InputAction m_PLAY_Skill;
    private readonly InputAction m_PLAY_Graffiti1;
    private readonly InputAction m_PLAY_Graffiti2;
    private readonly InputAction m_PLAY_Graffiti3;
    private readonly InputAction m_PLAY_Graffiti4;
    private readonly InputAction m_PLAY_Graffiti5;
    public struct PLAYActions
    {
        private @PlayerAction m_Wrapper;
        public PLAYActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PLAY_Move;
        public InputAction @MovePressedD => m_Wrapper.m_PLAY_MovePressedD;
        public InputAction @MovePressedR => m_Wrapper.m_PLAY_MovePressedR;
        public InputAction @MovePressedU => m_Wrapper.m_PLAY_MovePressedU;
        public InputAction @MovePressedL => m_Wrapper.m_PLAY_MovePressedL;
        public InputAction @Sprint => m_Wrapper.m_PLAY_Sprint;
        public InputAction @Attack => m_Wrapper.m_PLAY_Attack;
        public InputAction @Dodge => m_Wrapper.m_PLAY_Dodge;
        public InputAction @GraffitiSystem => m_Wrapper.m_PLAY_GraffitiSystem;
        public InputAction @Menu => m_Wrapper.m_PLAY_Menu;
        public InputAction @Confirm => m_Wrapper.m_PLAY_Confirm;
        public InputAction @Skill => m_Wrapper.m_PLAY_Skill;
        public InputAction @Graffiti1 => m_Wrapper.m_PLAY_Graffiti1;
        public InputAction @Graffiti2 => m_Wrapper.m_PLAY_Graffiti2;
        public InputAction @Graffiti3 => m_Wrapper.m_PLAY_Graffiti3;
        public InputAction @Graffiti4 => m_Wrapper.m_PLAY_Graffiti4;
        public InputAction @Graffiti5 => m_Wrapper.m_PLAY_Graffiti5;
        public InputActionMap Get() { return m_Wrapper.m_PLAY; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PLAYActions set) { return set.Get(); }
        public void AddCallbacks(IPLAYActions instance)
        {
            if (instance == null || m_Wrapper.m_PLAYActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PLAYActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @MovePressedD.started += instance.OnMovePressedD;
            @MovePressedD.performed += instance.OnMovePressedD;
            @MovePressedD.canceled += instance.OnMovePressedD;
            @MovePressedR.started += instance.OnMovePressedR;
            @MovePressedR.performed += instance.OnMovePressedR;
            @MovePressedR.canceled += instance.OnMovePressedR;
            @MovePressedU.started += instance.OnMovePressedU;
            @MovePressedU.performed += instance.OnMovePressedU;
            @MovePressedU.canceled += instance.OnMovePressedU;
            @MovePressedL.started += instance.OnMovePressedL;
            @MovePressedL.performed += instance.OnMovePressedL;
            @MovePressedL.canceled += instance.OnMovePressedL;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Dodge.started += instance.OnDodge;
            @Dodge.performed += instance.OnDodge;
            @Dodge.canceled += instance.OnDodge;
            @GraffitiSystem.started += instance.OnGraffitiSystem;
            @GraffitiSystem.performed += instance.OnGraffitiSystem;
            @GraffitiSystem.canceled += instance.OnGraffitiSystem;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Confirm.started += instance.OnConfirm;
            @Confirm.performed += instance.OnConfirm;
            @Confirm.canceled += instance.OnConfirm;
            @Skill.started += instance.OnSkill;
            @Skill.performed += instance.OnSkill;
            @Skill.canceled += instance.OnSkill;
            @Graffiti1.started += instance.OnGraffiti1;
            @Graffiti1.performed += instance.OnGraffiti1;
            @Graffiti1.canceled += instance.OnGraffiti1;
            @Graffiti2.started += instance.OnGraffiti2;
            @Graffiti2.performed += instance.OnGraffiti2;
            @Graffiti2.canceled += instance.OnGraffiti2;
            @Graffiti3.started += instance.OnGraffiti3;
            @Graffiti3.performed += instance.OnGraffiti3;
            @Graffiti3.canceled += instance.OnGraffiti3;
            @Graffiti4.started += instance.OnGraffiti4;
            @Graffiti4.performed += instance.OnGraffiti4;
            @Graffiti4.canceled += instance.OnGraffiti4;
            @Graffiti5.started += instance.OnGraffiti5;
            @Graffiti5.performed += instance.OnGraffiti5;
            @Graffiti5.canceled += instance.OnGraffiti5;
        }

        private void UnregisterCallbacks(IPLAYActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @MovePressedD.started -= instance.OnMovePressedD;
            @MovePressedD.performed -= instance.OnMovePressedD;
            @MovePressedD.canceled -= instance.OnMovePressedD;
            @MovePressedR.started -= instance.OnMovePressedR;
            @MovePressedR.performed -= instance.OnMovePressedR;
            @MovePressedR.canceled -= instance.OnMovePressedR;
            @MovePressedU.started -= instance.OnMovePressedU;
            @MovePressedU.performed -= instance.OnMovePressedU;
            @MovePressedU.canceled -= instance.OnMovePressedU;
            @MovePressedL.started -= instance.OnMovePressedL;
            @MovePressedL.performed -= instance.OnMovePressedL;
            @MovePressedL.canceled -= instance.OnMovePressedL;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Dodge.started -= instance.OnDodge;
            @Dodge.performed -= instance.OnDodge;
            @Dodge.canceled -= instance.OnDodge;
            @GraffitiSystem.started -= instance.OnGraffitiSystem;
            @GraffitiSystem.performed -= instance.OnGraffitiSystem;
            @GraffitiSystem.canceled -= instance.OnGraffitiSystem;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Confirm.started -= instance.OnConfirm;
            @Confirm.performed -= instance.OnConfirm;
            @Confirm.canceled -= instance.OnConfirm;
            @Skill.started -= instance.OnSkill;
            @Skill.performed -= instance.OnSkill;
            @Skill.canceled -= instance.OnSkill;
            @Graffiti1.started -= instance.OnGraffiti1;
            @Graffiti1.performed -= instance.OnGraffiti1;
            @Graffiti1.canceled -= instance.OnGraffiti1;
            @Graffiti2.started -= instance.OnGraffiti2;
            @Graffiti2.performed -= instance.OnGraffiti2;
            @Graffiti2.canceled -= instance.OnGraffiti2;
            @Graffiti3.started -= instance.OnGraffiti3;
            @Graffiti3.performed -= instance.OnGraffiti3;
            @Graffiti3.canceled -= instance.OnGraffiti3;
            @Graffiti4.started -= instance.OnGraffiti4;
            @Graffiti4.performed -= instance.OnGraffiti4;
            @Graffiti4.canceled -= instance.OnGraffiti4;
            @Graffiti5.started -= instance.OnGraffiti5;
            @Graffiti5.performed -= instance.OnGraffiti5;
            @Graffiti5.canceled -= instance.OnGraffiti5;
        }

        public void RemoveCallbacks(IPLAYActions instance)
        {
            if (m_Wrapper.m_PLAYActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPLAYActions instance)
        {
            foreach (var item in m_Wrapper.m_PLAYActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PLAYActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PLAYActions @PLAY => new PLAYActions(this);

    // MENU
    private readonly InputActionMap m_MENU;
    private List<IMENUActions> m_MENUActionsCallbackInterfaces = new List<IMENUActions>();
    private readonly InputAction m_MENU_Navigate;
    private readonly InputAction m_MENU_Submit;
    private readonly InputAction m_MENU_Cancel;
    private readonly InputAction m_MENU_Point;
    private readonly InputAction m_MENU_Click;
    private readonly InputAction m_MENU_ScrollWheel;
    private readonly InputAction m_MENU_MiddleClick;
    private readonly InputAction m_MENU_RightClick;
    private readonly InputAction m_MENU_TrackedDevicePosition;
    private readonly InputAction m_MENU_TrackedDeviceOrientation;
    public struct MENUActions
    {
        private @PlayerAction m_Wrapper;
        public MENUActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_MENU_Navigate;
        public InputAction @Submit => m_Wrapper.m_MENU_Submit;
        public InputAction @Cancel => m_Wrapper.m_MENU_Cancel;
        public InputAction @Point => m_Wrapper.m_MENU_Point;
        public InputAction @Click => m_Wrapper.m_MENU_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_MENU_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_MENU_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_MENU_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_MENU_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_MENU_TrackedDeviceOrientation;
        public InputActionMap Get() { return m_Wrapper.m_MENU; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MENUActions set) { return set.Get(); }
        public void AddCallbacks(IMENUActions instance)
        {
            if (instance == null || m_Wrapper.m_MENUActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MENUActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @ScrollWheel.started += instance.OnScrollWheel;
            @ScrollWheel.performed += instance.OnScrollWheel;
            @ScrollWheel.canceled += instance.OnScrollWheel;
            @MiddleClick.started += instance.OnMiddleClick;
            @MiddleClick.performed += instance.OnMiddleClick;
            @MiddleClick.canceled += instance.OnMiddleClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
        }

        private void UnregisterCallbacks(IMENUActions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @ScrollWheel.started -= instance.OnScrollWheel;
            @ScrollWheel.performed -= instance.OnScrollWheel;
            @ScrollWheel.canceled -= instance.OnScrollWheel;
            @MiddleClick.started -= instance.OnMiddleClick;
            @MiddleClick.performed -= instance.OnMiddleClick;
            @MiddleClick.canceled -= instance.OnMiddleClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @TrackedDevicePosition.started -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled -= instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled -= instance.OnTrackedDeviceOrientation;
        }

        public void RemoveCallbacks(IMENUActions instance)
        {
            if (m_Wrapper.m_MENUActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMENUActions instance)
        {
            foreach (var item in m_Wrapper.m_MENUActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MENUActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MENUActions @MENU => new MENUActions(this);

    // GRAFFITI
    private readonly InputActionMap m_GRAFFITI;
    private List<IGRAFFITIActions> m_GRAFFITIActionsCallbackInterfaces = new List<IGRAFFITIActions>();
    private readonly InputAction m_GRAFFITI_MovePressedD;
    private readonly InputAction m_GRAFFITI_MovePressedR;
    private readonly InputAction m_GRAFFITI_MovePressedU;
    private readonly InputAction m_GRAFFITI_MovePressedL;
    private readonly InputAction m_GRAFFITI_Attack;
    private readonly InputAction m_GRAFFITI_GraffitiSystem;
    private readonly InputAction m_GRAFFITI_Skill;
    private readonly InputAction m_GRAFFITI_Cancel;
    private readonly InputAction m_GRAFFITI_Graffiti1;
    private readonly InputAction m_GRAFFITI_Graffiti2;
    private readonly InputAction m_GRAFFITI_Graffiti3;
    private readonly InputAction m_GRAFFITI_Graffiti4;
    private readonly InputAction m_GRAFFITI_Graffiti5;
    public struct GRAFFITIActions
    {
        private @PlayerAction m_Wrapper;
        public GRAFFITIActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePressedD => m_Wrapper.m_GRAFFITI_MovePressedD;
        public InputAction @MovePressedR => m_Wrapper.m_GRAFFITI_MovePressedR;
        public InputAction @MovePressedU => m_Wrapper.m_GRAFFITI_MovePressedU;
        public InputAction @MovePressedL => m_Wrapper.m_GRAFFITI_MovePressedL;
        public InputAction @Attack => m_Wrapper.m_GRAFFITI_Attack;
        public InputAction @GraffitiSystem => m_Wrapper.m_GRAFFITI_GraffitiSystem;
        public InputAction @Skill => m_Wrapper.m_GRAFFITI_Skill;
        public InputAction @Cancel => m_Wrapper.m_GRAFFITI_Cancel;
        public InputAction @Graffiti1 => m_Wrapper.m_GRAFFITI_Graffiti1;
        public InputAction @Graffiti2 => m_Wrapper.m_GRAFFITI_Graffiti2;
        public InputAction @Graffiti3 => m_Wrapper.m_GRAFFITI_Graffiti3;
        public InputAction @Graffiti4 => m_Wrapper.m_GRAFFITI_Graffiti4;
        public InputAction @Graffiti5 => m_Wrapper.m_GRAFFITI_Graffiti5;
        public InputActionMap Get() { return m_Wrapper.m_GRAFFITI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GRAFFITIActions set) { return set.Get(); }
        public void AddCallbacks(IGRAFFITIActions instance)
        {
            if (instance == null || m_Wrapper.m_GRAFFITIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GRAFFITIActionsCallbackInterfaces.Add(instance);
            @MovePressedD.started += instance.OnMovePressedD;
            @MovePressedD.performed += instance.OnMovePressedD;
            @MovePressedD.canceled += instance.OnMovePressedD;
            @MovePressedR.started += instance.OnMovePressedR;
            @MovePressedR.performed += instance.OnMovePressedR;
            @MovePressedR.canceled += instance.OnMovePressedR;
            @MovePressedU.started += instance.OnMovePressedU;
            @MovePressedU.performed += instance.OnMovePressedU;
            @MovePressedU.canceled += instance.OnMovePressedU;
            @MovePressedL.started += instance.OnMovePressedL;
            @MovePressedL.performed += instance.OnMovePressedL;
            @MovePressedL.canceled += instance.OnMovePressedL;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @GraffitiSystem.started += instance.OnGraffitiSystem;
            @GraffitiSystem.performed += instance.OnGraffitiSystem;
            @GraffitiSystem.canceled += instance.OnGraffitiSystem;
            @Skill.started += instance.OnSkill;
            @Skill.performed += instance.OnSkill;
            @Skill.canceled += instance.OnSkill;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Graffiti1.started += instance.OnGraffiti1;
            @Graffiti1.performed += instance.OnGraffiti1;
            @Graffiti1.canceled += instance.OnGraffiti1;
            @Graffiti2.started += instance.OnGraffiti2;
            @Graffiti2.performed += instance.OnGraffiti2;
            @Graffiti2.canceled += instance.OnGraffiti2;
            @Graffiti3.started += instance.OnGraffiti3;
            @Graffiti3.performed += instance.OnGraffiti3;
            @Graffiti3.canceled += instance.OnGraffiti3;
            @Graffiti4.started += instance.OnGraffiti4;
            @Graffiti4.performed += instance.OnGraffiti4;
            @Graffiti4.canceled += instance.OnGraffiti4;
            @Graffiti5.started += instance.OnGraffiti5;
            @Graffiti5.performed += instance.OnGraffiti5;
            @Graffiti5.canceled += instance.OnGraffiti5;
        }

        private void UnregisterCallbacks(IGRAFFITIActions instance)
        {
            @MovePressedD.started -= instance.OnMovePressedD;
            @MovePressedD.performed -= instance.OnMovePressedD;
            @MovePressedD.canceled -= instance.OnMovePressedD;
            @MovePressedR.started -= instance.OnMovePressedR;
            @MovePressedR.performed -= instance.OnMovePressedR;
            @MovePressedR.canceled -= instance.OnMovePressedR;
            @MovePressedU.started -= instance.OnMovePressedU;
            @MovePressedU.performed -= instance.OnMovePressedU;
            @MovePressedU.canceled -= instance.OnMovePressedU;
            @MovePressedL.started -= instance.OnMovePressedL;
            @MovePressedL.performed -= instance.OnMovePressedL;
            @MovePressedL.canceled -= instance.OnMovePressedL;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @GraffitiSystem.started -= instance.OnGraffitiSystem;
            @GraffitiSystem.performed -= instance.OnGraffitiSystem;
            @GraffitiSystem.canceled -= instance.OnGraffitiSystem;
            @Skill.started -= instance.OnSkill;
            @Skill.performed -= instance.OnSkill;
            @Skill.canceled -= instance.OnSkill;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Graffiti1.started -= instance.OnGraffiti1;
            @Graffiti1.performed -= instance.OnGraffiti1;
            @Graffiti1.canceled -= instance.OnGraffiti1;
            @Graffiti2.started -= instance.OnGraffiti2;
            @Graffiti2.performed -= instance.OnGraffiti2;
            @Graffiti2.canceled -= instance.OnGraffiti2;
            @Graffiti3.started -= instance.OnGraffiti3;
            @Graffiti3.performed -= instance.OnGraffiti3;
            @Graffiti3.canceled -= instance.OnGraffiti3;
            @Graffiti4.started -= instance.OnGraffiti4;
            @Graffiti4.performed -= instance.OnGraffiti4;
            @Graffiti4.canceled -= instance.OnGraffiti4;
            @Graffiti5.started -= instance.OnGraffiti5;
            @Graffiti5.performed -= instance.OnGraffiti5;
            @Graffiti5.canceled -= instance.OnGraffiti5;
        }

        public void RemoveCallbacks(IGRAFFITIActions instance)
        {
            if (m_Wrapper.m_GRAFFITIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGRAFFITIActions instance)
        {
            foreach (var item in m_Wrapper.m_GRAFFITIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GRAFFITIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GRAFFITIActions @GRAFFITI => new GRAFFITIActions(this);

    // UI_TOGGLE
    private readonly InputActionMap m_UI_TOGGLE;
    private List<IUI_TOGGLEActions> m_UI_TOGGLEActionsCallbackInterfaces = new List<IUI_TOGGLEActions>();
    private readonly InputAction m_UI_TOGGLE_OpenMap;
    private readonly InputAction m_UI_TOGGLE_OpenNote;
    private readonly InputAction m_UI_TOGGLE_OpenCodex;
    public struct UI_TOGGLEActions
    {
        private @PlayerAction m_Wrapper;
        public UI_TOGGLEActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenMap => m_Wrapper.m_UI_TOGGLE_OpenMap;
        public InputAction @OpenNote => m_Wrapper.m_UI_TOGGLE_OpenNote;
        public InputAction @OpenCodex => m_Wrapper.m_UI_TOGGLE_OpenCodex;
        public InputActionMap Get() { return m_Wrapper.m_UI_TOGGLE; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UI_TOGGLEActions set) { return set.Get(); }
        public void AddCallbacks(IUI_TOGGLEActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_TOGGLEActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_TOGGLEActionsCallbackInterfaces.Add(instance);
            @OpenMap.started += instance.OnOpenMap;
            @OpenMap.performed += instance.OnOpenMap;
            @OpenMap.canceled += instance.OnOpenMap;
            @OpenNote.started += instance.OnOpenNote;
            @OpenNote.performed += instance.OnOpenNote;
            @OpenNote.canceled += instance.OnOpenNote;
            @OpenCodex.started += instance.OnOpenCodex;
            @OpenCodex.performed += instance.OnOpenCodex;
            @OpenCodex.canceled += instance.OnOpenCodex;
        }

        private void UnregisterCallbacks(IUI_TOGGLEActions instance)
        {
            @OpenMap.started -= instance.OnOpenMap;
            @OpenMap.performed -= instance.OnOpenMap;
            @OpenMap.canceled -= instance.OnOpenMap;
            @OpenNote.started -= instance.OnOpenNote;
            @OpenNote.performed -= instance.OnOpenNote;
            @OpenNote.canceled -= instance.OnOpenNote;
            @OpenCodex.started -= instance.OnOpenCodex;
            @OpenCodex.performed -= instance.OnOpenCodex;
            @OpenCodex.canceled -= instance.OnOpenCodex;
        }

        public void RemoveCallbacks(IUI_TOGGLEActions instance)
        {
            if (m_Wrapper.m_UI_TOGGLEActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUI_TOGGLEActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_TOGGLEActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_TOGGLEActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UI_TOGGLEActions @UI_TOGGLE => new UI_TOGGLEActions(this);
    public interface IPLAYActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMovePressedD(InputAction.CallbackContext context);
        void OnMovePressedR(InputAction.CallbackContext context);
        void OnMovePressedU(InputAction.CallbackContext context);
        void OnMovePressedL(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnGraffitiSystem(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnGraffiti1(InputAction.CallbackContext context);
        void OnGraffiti2(InputAction.CallbackContext context);
        void OnGraffiti3(InputAction.CallbackContext context);
        void OnGraffiti4(InputAction.CallbackContext context);
        void OnGraffiti5(InputAction.CallbackContext context);
    }
    public interface IMENUActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
    }
    public interface IGRAFFITIActions
    {
        void OnMovePressedD(InputAction.CallbackContext context);
        void OnMovePressedR(InputAction.CallbackContext context);
        void OnMovePressedU(InputAction.CallbackContext context);
        void OnMovePressedL(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnGraffitiSystem(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnGraffiti1(InputAction.CallbackContext context);
        void OnGraffiti2(InputAction.CallbackContext context);
        void OnGraffiti3(InputAction.CallbackContext context);
        void OnGraffiti4(InputAction.CallbackContext context);
        void OnGraffiti5(InputAction.CallbackContext context);
    }
    public interface IUI_TOGGLEActions
    {
        void OnOpenMap(InputAction.CallbackContext context);
        void OnOpenNote(InputAction.CallbackContext context);
        void OnOpenCodex(InputAction.CallbackContext context);
    }
}
